#!/bin/bash

### SDDM Autologin user: ralexander

### Disable warnning line
sed -i -e 's|^autogenerated = 1|# autogenerated = 1|' "$HOME/.config/hypr/hyprland.conf"
sleep 3

### Install yay
sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
sleep 5

bash flatpak install flathub com.ml4w.dotfilesinstaller
sleep 3

flatpak uninstall -y com.github.PintaProject.Pinta && flatpak uninstall -y com.ml4w.calendar && sleep 5 && clear

sudo sed -i '/^User=/s//User=ralexander/' /usr/lib/sddm/sddm.conf.d/default.conf
sleep 3

### run dotfileinstaller by hand
# https://raw.githubusercontent.com/mylinuxforwork/dotfiles/main/hyprland-dotfiles-stable.dotinst

