#!/bin/bash

# This is script to first run when restoring
# Will rsync home,dots,Srv folder to $HOME directory

### VAR
USB="/run/media/ralexander/netac"
DIRS=(Documents Pictures Obsidian Working Shared VM dots .icons .themes .ssh)

mkdir -p "$HOME/.config/Thunar"
mkdir -p "$HOME/.config/com.ml4w.hyprlandsettings"
mkdir -p "$HOME/.local/share/icons"

### run dotfileinstaller by hand
# https://raw.githubusercontent.com/mylinuxforwork/dotfiles/main/hyprland-dotfiles-stable.dotinst

### Disable warnning line
### SDDM Autologin user: ralexander
sed -i -e 's|^autogenerated = 1|# autogenerated = 1|' "$HOME/.config/hypr/hyprland.conf" && sleep 2
sudo sed -i '/^User=/s//User=ralexander/' /usr/lib/sddm/sddm.conf.d/default.conf && sleep 3


### Install yay
sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si && sleep 2

### flatpak dot-installer for ml4w
flatpak install flathub com.ml4w.dotfilesinstaller && sleep 2


for d in "${DIRS[@]}"; do
  rsync -Parh "$USB/home/$d" "$HOME"
  rsync -Prah "$USB/Srv" "$HOME" 
  rsync -Prah "$USB/dots" "$HOME"
  rsync -Prah "$USB/home/LyraX-cursors" "$HOME/.local/share/icons"
  rsync -Prah "$USB/dots/uca.xml" "$HOME/.config/Thunar"
done
sleep 2 ; clear


### Font install NerdFont 3.4.0
bash "$HOME/Shared/fonts/install.sh" ; sleep 2 ; clear

