#!/bin/bash

USB="/run/media/ralexander/netac"
DIRS=(Documents Pictures Obsidian Working Shared VM dots .icons .themes .ssh)

##### PRE RESTORE TODO
### SDDM Autologin user: ralexander
sudo sed -i '/^User=/s//User=ralexander/' /usr/lib/sddm/sddm.conf.d/default.conf

### Disable warnning line
sed -i -e 's|^autogenerated = 1|# autogenerated = 1|' "$HOME/.config/hypr/hyprland.conf"

cp -r "$USB/home/.icons" "$HOME"
cp -r "$USB/home/.themes" "$HOME"
mkdir -p "$HOME/.local/share/icons" && cp -r "$USB/home/.local/share/icons/LyraX-cursors" "$HOME/.local/share/icons"

### Check for installed
set -u
ensure_pacman_packages() {
# Accept packages as arguments or fall back to a default list
  local pkgs=("$@")
  if ((${#pkgs[@]} == 0)); then
    pkgs=(rsync)
  fi

##### if not root, then yes
  local SUDO=""
  if [[ $EUID -ne 0 ]]; then
    if command -v sudo >/dev/null 2>&1; then
      SUDO="sudo"
    else
      echo "Need root (sudo missing)... Skipping installed..."
      return 1
    fi
  fi

  local missing=()
  echo "Checking installed packages..."
  for pkg in "${pkgs[@]}"; do
    if pacman -Q "$pkg" >/dev/null 2>&1; then
      echo "✓ $pkg is installed... Skipping..."
    else
      echo "• $pkg is not installed... Will install..."
      missing+=("$pkg")
    fi
  done

  if ((${#missing[@]} == 0)); then
    echo "All already installed..."
    return 0
  fi

  echo "Installing missing: ${missing[*]}"
  if ! $SUDO pacman -S --needed --noconfirm "${missing[@]}"; then
    echo "Installation failed..."
    return 1
  fi

  echo "Package ensure step complete..."
  return 0
}

### use it like this
ensure_pacman_packages \
  rsync

for d in "${DIRS[@]}"; do
  rsync -Parh "$USB/home/$d" "$HOME" && cp -r "$USB/Srv" "$HOME" && cp -r "$USB/dots" "$HOME"
done
sleep 2 ; clear

